### ISSUE TITLE
이미지 최적화 관련

### ISSUE THREAD

**Issue by ykss** [Club-PARD/BrandMe_Front#61]
## 🌱 제목
이미지 최적화 관련

## 🌱 페이지
현재 홈에서 배경 gif랑 온보딩 png가 엄청 큰 용량이어서, 렌더링 시 눈에 띄게 느린거 같은데,
그것들만 webp, avif 같은 형식으로 변경해서 파일 크기만 줄여도 많이 개선이 있을 것 같네요! 
아래 링크랑 서비스 참고해보면 좋을 것 같아요!

https://velog.io/@hustle-dev/%EC%9B%B9-%EC%84%B1%EB%8A%A5%EC%9D%84-%EC%9C%84%ED%95%9C-%EC%9D%B4%EB%AF%B8%EC%A7%80-%EC%B5%9C%EC%A0%81%ED%99%94

https://convertio.co/kr

**Comment by eunoia-jaxson** [comment]
감사합니다!! 확인해 보겠습니다!
